### ISSUE TITLE
`Failed to load module script: JavaScript module script but the server responded with a MIME type of "text/plain". 

### ISSUE THREAD

**Issue by debpalash** [crxjs/chrome-extension-tools#537] opened 2022-10-17 01:26 UTC
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

### Reproduction

install using docs instruction

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7
    Memory: 10.11 GB / 15.92 GB
  Binaries:
    Node: 18.10.0 - C:\Program Files\nodejs\node.EXE     
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
   Chrome
  npmPackages:
    @crxjs/vite-plugin: ^1.0.14 => 1.0.14 
    vite: ^3.1.8 => 3.1.8
```

### Severity

blocking all usage of RPCE

**Comment by filipw01** [comment] 2022-10-17 06:59
`@crxjs/vite-plugin` version 1 does not support `vite` version 3. Try using `@crxjs/vite-plugin` version 2 beta (released yesterday)

**Comment by debpalash** [comment] 2022-10-17 12:44
> `@crxjs/vite-plugin` version 1 does not support `vite` version 3. Try using `@crxjs/vite-plugin` version 2 beta (released yesterday)

Th
![image](https://user-images.githubusercontent.com/4178343/196179752-5cd19592-14e0-408f-9297-b377e1a67b0b.png)



<details>
  <summary>pnpm run dev: error log</summary>
  ```js
 
> > vite-template-solid@0.0.0 start D:\chromeExtension\crxjs\vite-solid-crxjs
> vite

failed to load config from D:\chromeExtension\crxjs\vite-solid-crxjs\vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module D:\chromeExtension\crxjs\vite-solid-crxjs\node_modules\.pnpm\get-port@6.1.2\node_modules\get-port\index.js from D:\chromeExtension\crxjs\vite-solid-crxjs\node_modules\.pnpm\@crxjs+vite-plugin@2.0.0-beta.1_vite@3.1.8\node_modules\@crxjs\vite-plugin\dist\index.cjs not supported.     
Instead change the require of index.js in D:\chromeExtension\crxjs\vite-solid-crxjs\node_modules\.pnpm\@crxjs+vite-plugin@2.0.0-beta.1_vite@3.1.8\node_modules\@crxjs\vite-plugin\dist\index.cjs to a 
dynamic import() which is available in all CommonJS modules.      
    at _require.extensions.<computed> [as .js] (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63540:17)
    at Object.<anonymous> (D:\chromeExtension\crxjs\vite-solid-crxjs\node_modules\.pnpm\@crxjs+vite-plugin@2.0.0-beta.1_vite@3.1.8\node_modules\@crxjs\vite-plugin\dist\index.cjs:20:15)
    at _require.extensions.<computed> [as .js] (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63540:17)
    at Object.<anonymous> (D:\chromeExtension\crxjs\vite-solid-crxjs\vite.config.js:33:26)
    at _require.extensions.<computed> [as .js] (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63537:24)
    at loadConfigFromBundledFile (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63545:21)
    at loadConfigFromFile (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63409:34)
    at async resolveConfig (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:63026:28)
    at async createServer (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:62092:20)
    at async CAC.<anonymous> (file:///D:/chromeExtension/crxjs/vite-solid-crxjs/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/cli.js:700:24)
 ELIFECYCLE  Command failed with exit code 1.
  ```

**Comment by filipw01** [comment] 2022-10-17 12:55
For now you can try using `vite@3.1.7` and see if you have any issues there

**Comment by tylergets** [comment] 2022-10-18 21:56
I can confirm this errors still occurs with vite 3.1.7

**Comment by jacksteamdev** [comment] 2022-10-23 21:40
The peer deps problem should be fixed in the current beta release (v2.0.0-beta.2):

```sh
npm i -D @crxjs/vite-plugin@beta 
```

**Comment by cpakken** [comment] 2022-10-31 04:29
I get the same issue with latest vite and crx beta plugin
```json
{
  "name": "input",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@crxjs/vite-plugin": "2.0.0-beta.4",
    "@types/react": "^18.0.22",
    "@types/react-dom": "^18.0.7",
    "@vitejs/plugin-react": "^2.2.0",
    "typescript": "^4.6.4",
    "vite": "^3.2.0"
  }
}
```
![image](https://user-images.githubusercontent.com/61718569/198931300-cf96fff6-6832-434c-9bcd-900b143eedc7.png)

**Comment by jacksteamdev** [comment] 2022-11-06 16:58
I haven't been able to reproduce this specific error with the information provided.

The SolidJS template repo must be configured to use ESM to work with Vite 3. Please add `"type": "module"` to the package JSON file.

**Comment by jacksteamdev** [comment] 2022-11-06 18:16
I cannot reproduce this bug with CRXJS@2.0.0-beta.4 and Vite@3.2.2.

**Closed by jacksteamdev** 2022-11-06 18:16 UTC

**Comment by ezeikel** [comment] 2023-04-19 16:13
Getting the same issue using:

vite@4.2.2"
@crxjs/vite-plugin@2.0.0-beta.16

**Comment by faahim** [comment] 2023-05-14 12:56
Having the same issue as well.

"@crxjs/vite-plugin": "^1.0.14",
"vite": "^2.9.15"

**Comment by cscxj** [comment] 2023-07-31 09:54
The same problem.

"vite": "^4.4.5"
"@crxjs/vite-plugin": "2.0.0-beta.18"

**Comment by DeltaLaboratory** [comment] 2023-12-22 00:26
Same problem here

"vite": "^5.0.8"
"@crxjs/vite-plugin": "2.0.0-beta.21"

**Comment by danielkleinstein** [comment] 2023-12-24 10:48
This is the error that arises if you load the root folder of your project (i.e. the folder containing `vite.config.js` as the Chrome extension) - this is an easy mistake to make, what you really want to do is load the generated `dist` folder.

When you load the root folder, `index.html` will include something like:

```html
<script type="module" src="/src/main.tsx"></script>
```

Which will load the file directly from the Chrome extension folder - and Chrome by default will serve it as a plaintext file.

**Comment by rahulbansal16** [comment] 2024-07-11 17:08
so how to load it?

**Comment by rahulbansal16** [comment] 2024-07-11 17:18
![image](https://github.com/crxjs/chrome-extension-tools/assets/8466045/21ae3f53-93df-463a-922d-034282e89031)
That's how my code was

I tried doing it like this.
/dist/src/main.jsx
![image](https://github.com/crxjs/chrome-extension-tools/assets/8466045/ef7127f1-5f77-4cef-b1f1-762c34ab995a)

but it's giving file not found error.


I also tried like this

dist/src/main.jsx
![image](https://github.com/crxjs/chrome-extension-tools/assets/8466045/677ed2ed-ca44-45ce-8050-6efacdc9dffa)

**Comment by rahulbansal16** [comment] 2024-07-11 17:49
@danielkleinstein 
This is the folder that I am trying to load
![image](https://github.com/crxjs/chrome-extension-tools/assets/8466045/786757dd-7445-4bfc-84bb-572bebb649b4)

**Comment by danielkleinstein** [comment] 2024-07-11 18:58
Try removing the `/dist` prefix from your include

**Comment by rahulbansal16** [comment] 2024-07-11 19:00
The initial code is without the dist but it gives error of MIME type.
